import type { Project } from "../types";

// Single source of truth for the Projects section (cards + modal).
// Add, remove, or edit entries here — no component changes needed.
//
// Field reference:
//   img            cover image shown on the grid card (path under /public)
//   size           'large' spans 2 grid columns on desktop, 'small' spans 1
//   category       eyebrow text shown on the card and in the modal
//   description    paragraph shown only in the modal
//   photos         gallery shown in the modal carousel; each entry is
//                  { src, label? } — set label to 'Antes' or 'Después' on
//                  the photos that are part of a before/after pair, and
//                  omit it for plain gallery photos (e.g. "Baños" or
//                  "Interiorismo", which have no antes/después split)
//   type           must match one of the values in PROJECT_FILTERS below
//                  (besides 'Todos', which always shows every project)
export const PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Casa Bosquecitos',
    location: 'Provincia Buenos Aires',
    category: 'Reforma integral, ampliación y nueva fachada',
    year: '2021',
    img: '/bosquecitos/cover/bosquecitos_1.webp',
    size: 'large',
    description: 'Reforma integral que incluye ampliación de planta baja, rediseño completo de fachada y renovación de todos los espacios interiores. El proyecto integra el entorno natural con la vivienda mediante materiales cálidos y una paleta neutra.',
    photos: [
      { src: '/bosquecitos/antes/bosquecitos_1.webp', label: 'Antes' },
      { src: '/bosquecitos/antes/bosquecitos_2.webp', label: 'Antes' },
      { src: '/bosquecitos/antes/bosquecitos_3.webp', label: 'Antes' },
      { src: '/bosquecitos/antes/bosquecitos_4.webp', label: 'Antes' },
      { src: '/bosquecitos/antes/bosquecitos_5.webp', label: 'Antes' },
      { src: '/bosquecitos/antes/bosquecitos_6.webp', label: 'Antes' },
      { src: '/bosquecitos/despues/bosquecitos_1_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_2_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_3_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_4_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_5_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_6_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_7_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_8_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_9_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_10_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_11_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_12_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_13_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_14_despues.webp', label: 'Después' },
      { src: '/bosquecitos/despues/bosquecitos_15_despues.webp', label: 'Después' },
    ],
    type: 'Otros',
  },
  {
    id: 2,
    name: 'Casa Lomas',
    location: 'Provincia Buenos Aires',
    category: 'Reforma integral',
    year: '2026',
    img: '/lomas.webp',
    size: 'small',
    description: 'Reforma integral de vivienda unifamiliar en Lomas de Zamora. Intervención total de cocina, baños, living y dormitorios con criterios de diseño contemporáneo y optimización del espacio.',
    photos: [
      { src: '/lomas/antes/lomas_1.webp', label: 'Antes' },
      { src: '/lomas/antes/lomas_2.webp', label: 'Antes' },
      { src: '/lomas/antes/lomas_3.webp', label: 'Antes' },
      { src: '/lomas/antes/lomas_4.webp', label: 'Antes' },
      { src: '/lomas/despues/lomas_1.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_2.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_3.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_4.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_5.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_6.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_7.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_8.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_9.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_10.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_11.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_12.webp', label: 'Después' },
      { src: '/lomas/despues/lomas_13.webp', label: 'Después' },
    ],
    type: 'Otros',
  },
  {
    id: 3,
    name: 'Departamento Entre Ríos',
    location: 'Capital Federal',
    category: 'Reforma integral',
    year: '2026',
    img: '/entrerios/cover/rios_1.png',
    size: 'small',
    description: 'Reforma integral de departamento en planta baja con patio. Diseño de cocina abierta, remodelación de baños y renovación de terminaciones con materiales de alta durabilidad.',
    photos: [
      { src: '/entrerios/antes/rios_1.webp', label: 'Antes' },
      { src: '/entrerios/antes/rios_2.webp', label: 'Antes' },
      { src: '/entrerios/antes/rios_3.webp', label: 'Antes' },
      { src: '/entrerios/despues/rios_1.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_2.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_3.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_4.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_5.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_6.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_7.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_8.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_9.webp', label: 'Después' },
      { src: '/entrerios/despues/rios_10.webp', label: 'Después' },
    ],
    type: 'Residencial',
  },
  {
    id: 4,
    name: 'Departamento Viamonte',
    location: 'Capital Federal',
    category: 'Reforma integral',
    year: '2025',
    img: '/viamonte.webp',
    size: 'large',
    description: 'Reforma integral de departamento en el microcentro porteño. Rediseño del espacio para maximizar la funcionalidad con una estética cálida y contemporánea que dialoga con la arquitectura existente del edificio.',
    photos: [
      { src: '/viamonte/antes/viamonte_1.webp', label: 'Antes' },
      { src: '/viamonte/antes/viamonte_2.webp', label: 'Antes' },
      { src: '/viamonte/antes/viamonte_3.webp', label: 'Antes' },
      { src: '/viamonte/despues/viamonte_1.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_2.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_3.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_4.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_5.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_6.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_7.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_8.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_9.webp', label: 'Después' },
      { src: '/viamonte/despues/viamonte_10.webp', label: 'Después' },
    ],
    type: 'Residencial',
  },
  {
    id: 5,
    name: 'Baños',
    location: 'Buenos Aires',
    category: 'Reformas desde',
    year: '2022',
    img: '/baños.webp',
    size: 'small',
    description: 'Proyectos de reformas de baños residenciales con distintas tipologías. Cada intervención fue diseñada de manera personalizada según las necesidades y el perfil de cada cliente, logrando espacios funcionales y estéticos.',
    photos: [
      { src: '/baños_1.webp' },
      { src: '/baños_2.webp' },
      { src: '/baños_3.webp' },
      { src: '/baños_4.webp' },
      { src: '/baños_5.webp' },
      { src: '/baños_6.webp' },
      { src: '/baños_7.webp' },
      { src: '/baños_8.webp' },
      { src: '/baños_9.webp' },
    ],
    type: 'Otros',
  },
  {
    id: 6,
    name: 'Interiorismo',
    location: 'Buenos Aires',
    category: 'Proyectos',
    year: '2024',
    img: '/interiorismo.webp',
    size: 'small',
    description: 'Proyectos de interiorismo residencial y comercial desarrollados en distintas zonas de Buenos Aires. Cada proyecto refleja la identidad del cliente traducida en espacios únicos, con atención al detalle y coherencia estética.',
    photos: [
      { src: '/interiorismo/int_1.webp' },
      { src: '/interiorismo/int_2.webp' },
      { src: '/interiorismo/int_3.webp' },
      { src: '/interiorismo/int_4.webp' },
      { src: '/interiorismo/int_5.webp' },
      { src: '/interiorismo/int_6.webp' },
      { src: '/interiorismo/int_7.webp' },
      { src: '/interiorismo/int_8.webp' },
      { src: '/interiorismo/int_9.webp' },
      { src: '/interiorismo/int_10.webp' },
      { src: '/interiorismo/int_11.webp' },
      { src: '/interiorismo/int_12.webp' },
      { src: '/interiorismo/int_13.webp' },
      { src: '/interiorismo/int_14.webp' },
      { src: '/interiorismo/int_15.webp' },
    ],
    type: 'Interiorismo',
  },
   {
    id: 7,
    name: 'craig',
    location: 'Capital Federal',
    category: 'Reforma integral',
    year: '2026',
    img: '/entre_rios.webp',
    size: 'small',
    description: 'Reforma integral de departamento en planta baja con patio. Diseño de cocina abierta, remodelación de baños y renovación de terminaciones con materiales de alta durabilidad.',
    photos: [
      { src: '/craig/antes/craig_1.webp', label: 'Antes' },
      { src: '/craig/antes/craig_2.webp', label: 'Antes' },
      { src: '/craig/antes/craig_3.webp', label: 'Antes' },
      { src: '/craig/antes/craig_4.webp', label: 'Antes' },
      { src: '/craig/despues/craig_1.webp', label: 'Después' },
      { src: '/craig/despues/craig_2.webp', label: 'Después' },
      { src: '/craig/despues/craig_3.webp', label: 'Después' },
      { src: '/craig/despues/craig_4.webp', label: 'Después' },
      { src: '/craig/despues/craig_5.webp', label: 'Después' },
      { src: '/craig/despues/craig_6.webp', label: 'Después' },
      { src: '/craig/despues/craig_7.webp', label: 'Después' },
      { src: '/craig/despues/craig_8.webp', label: 'Después' },
      { src: '/craig/despues/craig_9.webp', label: 'Después' },
    ],
    type: 'Residencial',
  },
     {
    id: 8,
    name: 'gallo',
    location: 'Capital Federal',
    category: 'Reforma integral',
    year: '2026',
    img: '/entre_rios.webp',
    size: 'small',
    description: 'Reforma integral de departamento en planta baja con patio. Diseño de cocina abierta, remodelación de baños y renovación de terminaciones con materiales de alta durabilidad.',
    photos: [
      { src: '/gallo/despues/gallo_1.webp'},
      { src: '/gallo/despues/gallo_2.webp'},
      { src: '/gallo/despues/gallo_3.webp'},
      { src: '/gallo/despues/gallo_4.webp'},
      { src: '/gallo/despues/gallo_5.webp'},
      { src: '/gallo/despues/gallo_6.webp'},
      { src: '/gallo/despues/gallo_7.webp'},
      { src: '/gallo/despues/gallo_8.webp'},
      { src: '/gallo/despues/gallo_9.webp'},
      
    ],
    type: 'Residencial',
  },
];

// Filter tabs shown above the grid. 'Todos' is handled separately in
// Projects.tsx and always shows every project; the rest must match a
// project's `type` above exactly to appear in that tab.
export const PROJECT_FILTERS = ['Todos', 'Residencial', 'Interiorismo'];
